baseurl = "https://cedarbye.github.io/"
languageCode = "zh-CN"
title = "cedar's blog"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
disqusShortname = "cedarbye"
#theme = "hugo-minimalist-theme"

[params]
    site_author = "cedar"
    site_description = "The awesome blog of cedar."
    location = "Tianjin China"
    # All paths are relative to the baseurl. Put your files
    # somewhere in the static folder.
    avatar = "img/profile-image.png"
    header_background = "img/desk.jpg"
    header_title = "Notebook of Thinking"
    copyright = "Powered by [Hugo](http://gohugo.io)."

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = ""
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "cedarbye"
    gplus     = ""
